### ISSUE TITLE
Add bios to project

### ISSUE THREAD

**Issue by hubyeti** [ChadH1971/github-for-developers-7#3]
We should all create great bios in this project. Make sure your bio includes:

         - [ ] Your name
         - [ ] Where you are from
         - [ ] A favorite food
         - [ ] A hobby

**Comment by ChadH1971** [comment]
My name is Chad Hidalgo
I am from Brea, CA. I currently reside in Bakersfield, CA
One of my favorite foods is Macaroni and Cheese
A have many hobbies, my favorite and most expensive is scuba diving.
